### ISSUE TITLE
email notifications should be sent to all scidb operators

### ISSUE THREAD

**Issue by ksens** [Paradigm4/revealgenomics-ui-modules#10]
Requested by customer A:

When regular user logs in and requests permissions to studies, email currently goes to one scidb admin (the admin's email is maintained in the app's config file).

A few more changes to accompany the usage of "operator" users as requested in #7 , 
- [ ] the config file should instead include a list of usernames and emails should exist for all the elevated users ("operators"-s). 
- [ ] When regular user requests access, e-mails should go out to all operators simultaneously.

**Comment by arko-bhattacharya** [comment]
@ksens assigning to you.

**Comment by ksens** [comment]
Tested and deployed at customer A. Closing issue. 

Also updated the sample config file via commit https://github.com/Paradigm4/revealgenomics-ui-modules/commit/f6a297ce69706e1022bbd4859f67aa137370127b
