### ISSUE TITLE
Providing incorrect username and password leads to unusual state

### ISSUE THREAD

**Issue by ksens** [Paradigm4/revealgenomics-ui-modules#11]
Currently, if username - password combo is incorrect, the UI goes to a blank state where there is no option to try logging in again. 

Ideally, there should be a message that username / password was incorrect, and user should be provided option to try logging in again. 

Alternatively, there could be a "Try logging in again" button on the blank screen which would bring back the user to the original login dialog box.

**Comment by arko-bhattacharya** [comment]
Resolved.

**Comment by ksens** [comment]
Tested at customer A. Closing.
