### ISSUE TITLE
user notifications: Minor requests

### ISSUE THREAD

**Issue by ksens** [Paradigm4/revealgenomics-ui-modules#17]
Minor items as follow up to #16:

- [x] Typo: "Access to the ... have been granted / denied" should become "Access to the ... has been granted / denied" (IMO, "access" is the subject here)
- [x] Read prompt for email domain name from config file instead of hardcoding (related:  https://github.com/Paradigm4/revealgenomics-ui-modules/commit/86709d5a5e12b360610999d8c1f9f8eb9b3534e6). Custom domain name shared here privately.
- [x] In case of access granted, provide link to go to app (read this from custom config file; link shared [here](https://github.com/Paradigm4/cs-private-notes-space/blob/master/customer-code-names/README.md#deployment-a-url-s) privately)
- [x] When scidbadmin takes action on multiple studies, email subject includes only name of first study on list. Instead it is OK to have generic subject line like: "Update - Request for access to multiple studies approved" (Keep the specific email subject when action is taken on single study)

**Comment by ksens** [comment]
Updated and appended another item to ticket (please read directly on Github).

**Comment by arko-bhattacharya** [comment]
Completed above requests. Please review.

**Comment by ksens** [comment]
All items seemed to have been covered. Thanks. Closing issue.
