### ISSUE TITLE
user notifications: Access denied by admin results in multiple emails to requester

### ISSUE THREAD

**Issue by ksens** [Paradigm4/revealgenomics-ui-modules#18]
@arko-bhattacharya Follow up to #16:

Got two identical emails from the app when scidbadmin denies access on multiple studies at a time.

Get only one email from app in case of simultaneous access approval (i.e. as expected).

**Comment by arko-bhattacharya** [comment]
Completed above request. Please review.

**Comment by ksens** [comment]
Seems to have been covered. Thanks. Closing issue.
