### ISSUE TITLE
user notifications: Blank email id in operator / scidbadmin view

### ISSUE THREAD

**Issue by ksens** [Paradigm4/revealgenomics-ui-modules#19]
@arko-bhattacharya 

Follow-up to #16 -- as described below, blank emailid in scidbadmin / operator view does come up from time to time. However, email does go to the appropriate person. I do not have a repro -- keep a lookout for this when you test on your end. 

Marking as priority 2. 

### Notes 

Writing down my notes while integrating the updates to the UI. 

...
`3`. Logged in again as a regular user `ksenshar`, and requested access to three studies (two new ones, and one of the ones which I had already requested before, but scidbdmin had not given access to yet). email went to scidbadmin as expected. Then I logged in as scidbadmin user, and found the following screen:

![image](https://user-images.githubusercontent.com/13973052/64524609-81b24600-d31c-11e9-93a6-6d4dab505131.png)

One of the entries does not have emailid -- this piece was unexpected. 

Used root login to reject access to study that did not have emailid displayed, and grant access to another study. Received following notification emails

> Hi ksenshar,
> Access to the following study has been denied.
> -- Study 2
> Please contact admin for further details.
> 
> Have a good day!
> Admin

email 2

> Hi ksenshar,
> Access to the following study has been approved.
> -- Study 3
> 
> Have a good day!
> Admin
> 

_Originally posted by @ksens in https://github.com/Paradigm4/revealgenomics-ui-modules/issues/16#issuecomment-529413663_

**Comment by arko-bhattacharya** [comment]
Completed above request. Please review.

**Comment by ksens** [comment]
Not able to repro this issue any more. Thanks for the fix.
